import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/createSlideStage.ts',
    'src/deck/loadDeck.ts',
    'src/deck/manifestSchema.ts',
    'src/deck/pathSafety.ts',
    'src/deck/rewriteHtml.ts',
    'src/deck/trustCapabilities.ts',
    'src/deck/types.ts',
    'src/converter/buildManifest.ts',
    'src/converter/folderFilter.ts',
    'src/converter/htmlBlocks.ts',
    'src/converter/index.ts',
    'src/converter/mirrorExternal.ts',
    'src/converter/pack.ts',
    'src/converter/report.ts',
    'src/converter/singleHtml.ts',
    'src/converter/sniffer.ts',
    'src/converter/sources.ts',
    'src/converter/speakerNotes.ts',
    'src/converter/splitInlineDeck.ts',
    'src/converter/splitRouter.ts',
    'src/converter/splitWebComponent.ts',
    'src/converter/wrapSource.ts',
  ],
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: 'es2022',
  external: ['fflate', 'zod'],
  outDir: 'dist',
});
