import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/litePreset.tsx',
    'src/app/ConverterPanel.tsx',
    'src/app/Footer.tsx',
    'src/app/LanguageSwitcher.tsx',
    'src/app/LiteApp.tsx',
    'src/app/TrustPrompt.tsx',
    'src/app/UpdateBanner.tsx',
    'src/app/readFolderInput.ts',
    'src/browser/stageServiceWorker.ts',
    'src/desktop/MonitorPicker.tsx',
    'src/desktop/audienceWindow.ts',
    'src/desktop/closeGuard.ts',
    'src/desktop/env.ts',
    'src/desktop/fileOpen.ts',
    'src/desktop/monitors.ts',
    'src/desktop/openExternal.ts',
    'src/desktop/thumbnailCache.ts',
    'src/desktop/thumbnailCapture.ts',
    'src/desktop/updateCheck.ts',
    'src/desktop/useThumbnailCapture.ts',
    'src/export/buildSlidesPdf.ts',
    'src/export/downloadPdf.ts',
    'src/export/downloadStage.ts',
    'src/export/exportEditedStage.ts',
    'src/export/slidePdfCapture.ts',
    'src/export/useDeckPdfExport.ts',
    'src/i18n/I18nProvider.tsx',
    'src/i18n/detect.ts',
    'src/i18n/locales.ts',
    'src/i18n/messages.ts',
    'src/persistence/annotationStore.ts',
    'src/persistence/editsStore.ts',
    'src/persistence/legacyMigration.ts',
    'src/persistence/notesStore.ts',
    'src/persistence/trustStore.ts',
    'src/viewer/AudienceView.tsx',
    'src/viewer/DeckViewer.tsx',
    'src/viewer/useDeckEdits.ts',
    'src/viewer/useUnsavedExitGuard.ts',
  ],
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: 'es2022',
  external: [
    'react',
    'react-dom',
    /^react\//,
    /^react-dom\//,
    'lucide-react',
    'pdf-lib',
    /^@slidestage\//,
    /^@tauri-apps\//,
  ],
  outDir: 'dist',
});
