import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/i18n/translator.tsx',
    'src/markdown/renderMarkdown.ts',
    'src/markdown/MarkdownView.tsx',
    'src/viewer/AudienceView.tsx',
    'src/viewer/DeckStage.tsx',
    'src/viewer/DeckViewer.tsx',
    'src/viewer/DeckViewerHeader.tsx',
    'src/viewer/NotesPanel.tsx',
    'src/viewer/Overview.tsx',
    'src/viewer/PresenterSideRail.tsx',
    'src/viewer/PresenterStageBlock.tsx',
    'src/viewer/SpeakerNotesPanel.tsx',
    'src/viewer/SpeakerPanel.tsx',
    'src/viewer/useAudiencePointerTracking.ts',
    'src/viewer/useDeckViewerResize.ts',
    'src/viewer/useStageLayout.ts',
    'src/viewer/viewMath.ts',
    'src/presenter/AnnotationOverlay.tsx',
    'src/presenter/Blackout.tsx',
    'src/presenter/LaserPointer.tsx',
    'src/presenter/SelectionOverlay.tsx',
    'src/presenter/Spotlight.tsx',
    'src/presenter/Toolbar.tsx',
    'src/presenter/types.ts',
    'src/presenter/usePersistedNumber.ts',
    'src/presenter/usePresentationSync.ts',
    'src/presenter/usePresenter.ts',
    'src/presenter/slideRuntime.ts',
    'src/presenter/useSlideBridge.ts',
    'src/presenter/transport/broadcastChannel.ts',
    'src/presenter/transport/index.ts',
    'src/presenter/transport/tauriEvent.ts',
    'src/presenter/transport/types.ts',
  ],
  format: ['esm'],
  dts: true,
  sourcemap: true,
  clean: true,
  splitting: true,
  treeshake: true,
  target: 'es2022',
  external: [
    'react',
    'react-dom',
    /^react\//,
    /^react-dom\//,
    'lucide-react',
    /^@slidestage\//,
    /^@tauri-apps\//,
  ],
  outDir: 'dist',
});
